### ISSUE TITLE
Agrega las pruebas

### ISSUE THREAD

**Issue by devarops** [IslasGECI/tablero_front#3]
Hay que agregar pruebas resistentes a mutaciones para `public_html/js/json2table.js`

**Comment by devarops** [comment]
Dado que es en JavaScript, vamos a esperar que @nepito y @evaristor echen a andar el Stryker

**Comment by GenaroVel** [comment]
@nepito y @evaristor  estan trabajando en tomates en la tarjeta [GECI-13](https://app.gitkraken.com/glo/card/537944f08f39460b9c05df52f1b15ba0), ya estan las pruebas corriendo y los mutantes corriendo en el repo de [ejemplo_typescript](https://github.com/IslasGECI/ejemplo_typescript).

**Comment by devarops** [comment]
Ahora estamos avanzando aquí: [`gatsby-theme-atom-service`](https://github.com/nepito/gatsby-theme-atom-service)

**Comment by nepito** [comment]
En este [Issue](https://github.com/IslasGECI/ejemplo_typescript/issues/6) está la lista de pendientes

**Comment by evaristor** [comment]
Seguimos trabajando aquí:

- [ ] [ejemplo_typescript #6](https://github.com/IslasGECI/ejemplo_typescript/issues/6)
- [ ] [GECI-13](https://app.gitkraken.com/glo/card/537944f08f39460b9c05df52f1b15ba0)
- [ ] [gatsby-theme-atom-service](https://github.com/nepito/gatsby-theme-atom-service)

**Comment by devarops** [comment]
@nepito ¿Tú sabes cuál es el estado de este _issue_?

**Comment by nepito** [comment]
@evaristor En el _pr_ #15 están los primeros pasos para cerrar esté _issue_.
