### ISSUE TITLE
Grafica serie de tiempo de éxitos (PASS) y fracasos (FAIL)

### ISSUE THREAD

**Issue by devarops** [IslasGECI/tablero_front#5]
Serie de tiempo de total de objetivos que se construyeron mediante `geci-testmake` y serie de tiempo de los que no se pudieron contruir

**Comment by evaristor** [comment]
Esto ya no tiene sentido ahora que todos están pasando siempre

**Comment by devarops** [comment]
Esto ya no tiene sentido ahora que todos están pasando siempre
